[2023-12-04 00:18:03,240] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.model_preparation manual__2023-12-03T19:17:50.636636+00:00 [queued]>
[2023-12-04 00:18:03,245] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: water_polution.model_preparation manual__2023-12-03T19:17:50.636636+00:00 [queued]>
[2023-12-04 00:18:03,245] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 00:18:03,245] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-12-04 00:18:03,245] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-04 00:18:03,274] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): model_preparation> on 2023-12-03 19:17:50.636636+00:00
[2023-12-04 00:18:03,277] {standard_task_runner.py:52} INFO - Started process 34875 to run task
[2023-12-04 00:18:03,295] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'water_polution', 'model_preparation', 'manual__2023-12-03T19:17:50.636636+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/water_polution.py', '--cfg-path', '/tmp/tmpqsocsh95', '--error-file', '/tmp/tmptuezsdhh']
[2023-12-04 00:18:03,296] {standard_task_runner.py:80} INFO - Job 29: Subtask model_preparation
[2023-12-04 00:18:03,372] {task_command.py:369} INFO - Running <TaskInstance: water_polution.model_preparation manual__2023-12-03T19:17:50.636636+00:00 [running]> on host MLops.myguest.virtualbox.org
[2023-12-04 00:18:03,462] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=water_polution
AIRFLOW_CTX_TASK_ID=model_preparation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T19:17:50.636636+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T19:17:50.636636+00:00
[2023-12-04 00:18:03,463] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-04 00:18:03,465] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/antosha/project/scripts/model_preparation.py']
[2023-12-04 00:18:03,480] {subprocess.py:85} INFO - Output:
[2023-12-04 00:18:05,726] {subprocess.py:92} INFO - 2023/12/04 00:18:05 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - The git executable must be specified in one of the following ways:
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     - be included in your $PATH
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     - explicitly set via git.refresh()
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - 
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - All git commands will error until this is rectified.
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - 
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - This initial warning can be silenced or aggravated in the future by setting the
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     - quiet|q|silence|s|none|n|0: for no warning or exception
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     - warn|w|warning|1: for a printed warning
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     - error|e|raise|r|2: for a raised exception
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - 
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - Example:
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO -     export GIT_PYTHON_REFRESH=quiet
[2023-12-04 00:18:05,727] {subprocess.py:92} INFO - 
[2023-12-04 00:18:06,941] {subprocess.py:92} INFO - /home/antosha/venvs/practice_3/lib/python3.10/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2023-12-04 00:18:06,941] {subprocess.py:92} INFO -   y = column_or_1d(y, warn=True)
[2023-12-04 00:18:12,234] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-04 00:18:12,256] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=water_polution, task_id=model_preparation, execution_date=20231203T191750, start_date=20231203T191803, end_date=20231203T191812
[2023-12-04 00:18:12,304] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-04 00:18:12,329] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
